# Generated by Django 4.2.8 on 2023-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password_change_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
